version: "3.8"

services:
  app:
    build: .
    container_name: cmms-oracle-spring
    env_file:
      - .env
    environment:
      - ORACLE_USE_WALLET=${ORACLE_USE_WALLET:-false}
      - ORACLE_WALLET_PATH=${ORACLE_WALLET_PATH:-/opt/oracle/wallet}
      - ORACLE_HOST=${ORACLE_HOST}
      - ORACLE_PORT=${ORACLE_PORT:-1521}
      - ORACLE_SERVICE=${ORACLE_SERVICE}
      - ORACLE_USER=${ORACLE_USER}
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_REGION=${S3_REGION:-us-ashburn-1}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE:-false}
      - PORT=${PORT:-8080}
      - JWT_SECRET=${JWT_SECRET:-change-this-secret}
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - ./:/workspace:delegated
      - ${ORACLE_WALLET_LOCAL_PATH:-./oracle_wallet}:${ORACLE_WALLET_PATH:-/opt/oracle/wallet}:ro
    networks:
      - cmms-net

networks:
  cmms-net:
    driver: bridge
