platform :ios, '13.0'

require_relative '../node_modules/expo/scripts/autolinking'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

install! 'cocoapods', :deterministic_uuids => false

prepare_react_native_project!

# Flipper
flipper_config = FlipperConfiguration.disabled
if ENV['NO_FLIPPER'] == '1'
  flipper_config = FlipperConfiguration.disabled
elsif podfile_properties.key?('ios.flipper')
  if podfile_properties['ios.flipper'] == 'true'
    flipper_config = FlipperConfiguration.enabled(["Debug", "Release"])
  elsif podfile_properties['ios.flipper'] != 'false'
    flipper_config = FlipperConfiguration.enabled(["Debug", "Release"], { 'Flipper' => podfile_properties['ios.flipper'] })
  end
end

target 'AtlasCMMS' do
  use_expo_modules!
  config = use_native_modules!

  # (Optionnel) use_frameworks
  # if podfile_properties['ios.useFrameworks']
  #   use_frameworks! linkage: podfile_properties['ios.useFrameworks'].to_sym
  # elsif ENV['USE_FRAMEWORKS']
  #   use_frameworks! linkage: ENV['USE_FRAMEWORKS'].to_sym
  # end

  flags = get_default_flags()

  use_react_native!(
    path: config[:reactNativePath],
    hermes_enabled: false,                              # iOS -> JSC
    fabric_enabled: flags[:fabric_enabled],
    app_path: "#{Pod::Config.instance.installation_root}/..",
    flipper_configuration: flipper_config
  )

  # headers modulaires pour Firebase/GoogleUtilities
  pod 'FirebaseCore', :modular_headers => true
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      mac_catalyst_enabled: false
    )

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results.each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |cfg|
          cfg.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end

    # 🔧 Désactiver Bitcode partout + forcer dSYM
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |cfg|
        cfg.build_settings['ENABLE_BITCODE'] = 'NO'
        cfg.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
      end

      # ✅ Patch Folly pour Xcode 15 / iOS 17
      if t.name == 'RCT-Folly'
        t.build_configurations.each do |cfg|
          cfg.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          cfg.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FOLLY_HAVE_CLOCK_GETTIME=1'
          cfg.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FOLLY_NO_CONFIG=1' << 'FOLLY_MOBILE=1' << 'FOLLY_USE_LIBCPP=1'
        end
      end
    end
  end

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
end
